version: '3'

services:
  api:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./src:/bapi:ro
    environment:
      DEBUG: 'True'
      APM: 'False' #Set to True to enable APM logging
      APM_URL: 'http://0.0.0.0:8200'
      APM_DEBUG: 'True'
      APM_TOKEN: '' #Leave empty if you aren't using a token
      UWSGI_USER: 'www-data'
      UWSGI_GROUP: 'www-data'
      UWSGI_THREADS: 10
      UWSGI_PROCESSES: 2
      UWSGI_OFFLOAD_THREADS: 10
