patreon-goals: [12500, 20000] # Once one goal is met it will change to the next
items-per-page: 30

website-url: "http://192.168.1.110:8080"
api-url: "http://192.168.1.110:8081/"

request-source: "bapi"
