- id: 'nsv_tupelo'
  aliases:
    - 'nsv'
    - 'tupelo'
    - 'ftl2'
  name: 'NSV 13'
  nickname: 'NSV'
  host: '192.168.0.75'
  port: 7777
  open: true
  color: '150, 0, 0'
  rules_url: 'https://nsv.beestation13.com/wiki/Rules'
