name: python_linter
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  run_linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tools
        run: pip install black codespell flake8 isort safety
      - name: Check formatting & syntax
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
          flake8_args: "--select=E9,F63,F7,F82"
      - name: Check import sorting
        run: isort --check-only --profile black .
      - name: Check requirements
        run: pip install -r requirements.txt
      - name: Check for vulnerabilities
        run: safety check
      - name: Spellcheck
        run: codespell
