name: python_linter
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black codespell flake8 isort safety
      - run: black --check . || true
      - run: codespell || true
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics #Showstoppers
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || true
      - run: safety check
